Config = {}

Config.bodyParts = {
    [11816] = {["part"] = "Pelvis", ["boneIndex"] = 11816},
    [58271] = {["part"] = "Left Thigh", ["boneIndex"] = 58271},
    [47495] = {["part"] = "Mouth", ["boneIndex"] = 47495},
    [14201] = {["part"] = "Left Foot", ["boneIndex"] = 14201},
    [46078] = {["part"] = "Left Knee", ["boneIndex"] = 46078},
    [51826] = {["part"] = "Right Thigh", ["boneIndex"] = 51826},
    [24816] = {["part"] = "Spine Lower", ["boneIndex"] = 24816},
    [52301] = {["part"] = "Right Foot", ["boneIndex"] = 52301},
    [16335] = {["part"] = "Right Knee", ["boneIndex"] = 16335},
    [24817] = {["part"] = "Spine Mid", ["boneIndex"] = 24817},
    [60309] = {["part"] = "Left Hand", ["boneIndex"] = 60309},
    [22711] = {["part"] = "Left Elbow", ["boneIndex"] = 22711},
    [57005] = {["part"] = "Right Hand", ["boneIndex"] = 57005},
    [2992] = {["part"] = "Right Elbow", ["boneIndex"] = 2992},
    [39317] = {["part"] = "Neck", ["boneIndex"] = 39317},
    [31086] = {["part"] = "Head", ["boneIndex"] = 31086},
    [24818] = {["part"] = "Spine High", ["boneIndex"] = 24818},
    [64729] = {["part"] = "Left Clavicle", ["boneIndex"] = 64729},
    [26610] = {["part"] = "Left Finger Pinky", ["boneIndex"] = 26610},
    [26611] = {["part"] = "Left Finger Index", ["boneIndex"] = 26611},
    [26612] = {["part"] = "Left Finger Middle", ["boneIndex"] = 26612},
    [26613] = {["part"] = "Left Finger Ring", ["boneIndex"] = 26613},
    [26614] = {["part"] = "Left Finger Thumb", ["boneIndex"] = 26614},
    [10706] = {["part"] = "Right Clavicle", ["boneIndex"] = 10706},
    [58866] = {["part"] = "Right Finger Pinky", ["boneIndex"] = 58866},
    [58867] = {["part"] = "Right Finger Index", ["boneIndex"] = 58867},
    [58868] = {["part"] = "Right Finger Middle", ["boneIndex"] = 58868},
    [58869] = {["part"] = "Right Finger Ring", ["boneIndex"] = 58869},
    [58870] = {["part"] = "Right Finger Thumb", ["boneIndex"] = 58870},
    [21550] = {["part"] = "Face Left CheekBone", ["boneIndex"] = 21550},
    [19336] = {["part"] = "Face Right CheekBone", ["boneIndex"] = 19336},
    [37193] = {["part"] = "Forehead", ["boneIndex"] = 37193},
    [61839] = {["part"] = "Face UpperLip", ["boneIndex"] = 61839},
    [20623] = {["part"] = "Face LowerLip", ["boneIndex"] = 20623},
}

Config.Weapons = {
    [GetHashKey('WEAPON_UNARMED')] = 'Unarmed',
    [GetHashKey('WEAPON_G43X')] = 'Glock 43x',
    [GetHashKey('WEAPON_BP')] = 'Beretta Pico',
    [GetHashKey('WEAPON_B70')] = 'Beretta b70',
    [GetHashKey('WEAPON_19M')] = 'Makarov 19',
    [GetHashKey('WEAPON_SHRP')] = 'Sig Sauer P320',
    [GetHashKey('WEAPON_G17S')] = 'Glock 17 (Switch)',
    [GetHashKey('WEAPON_HL')] = '(SERVICE) Hawk & Little Gardone',
    [GetHashKey('WEAPON_C357')] = '(SERVICE) Coonan.357 Magnum',
    [GetHashKey('WEAPON_PDARP')] = '(SERVICE) Assault rifle',
    [GetHashKey('WEAPON_HP')] = 'Hi Point',
    [GetHashKey('WEAPON_PISTOL50')] = 'Pistol .50',
    [GetHashKey('WEAPON_MICROSMG')] = 'Micro SMG',
    [GetHashKey('WEAPON_SMG')] = 'SMG',
    [GetHashKey('WEAPON_G17')] = 'Glock 17',
    [GetHashKey('WEAPON_SR40')] = 'Ruger SR40',
    [GetHashKey('WEAPON_P250')] = 'Sig Sauer P250 Compact',
    [GetHashKey('WEAPON_B92')] = 'Beretta 92FS',
    [GetHashKey('WEAPON_G19X')] = 'Glock 19x',
    [GetHashKey('WEAPON_SWITCHBLUE')] = 'Glock with a switch (Blue)',
    [GetHashKey('WEAPON_SWITCHGOLD')] = 'Glock with a switch (Gold)',
    [GetHashKey('WEAPON_MICRODRAC')] = 'Semi Auto Draco',
    [GetHashKey('WEAPON_PAINTGUN')] = 'Paintball Gun',
    [GetHashKey('WEAPON_G20')] = 'Glock 20',
    [GetHashKey('WEAPON_TEC9')] = 'Tec-9',
    [GetHashKey('WEAPON_XL')] = 'Staccato 2011',
    [GetHashKey('WEAPON_STUNGUN')] = 'Stun Gun',
    [GetHashKey('WEAPON_PFC9')] = 'P80 PFC9',
    [GetHashKey('WEAPON_USPT')] = 'H&K USP Tactical',
    [GetHashKey('WEAPON_G17')] = 'Glock 17',
    [GetHashKey('WEAPON_G17F')] = 'Glock 17 With A Flashlight',
    [GetHashKey('WEAPON_TX22')] = 'Taurus TX22',
    [GetHashKey('WEAPON_G17G5')] = 'Glock 17 Gen 5',
    [GetHashKey('WEAPON_P229')] = 'Sig Sauer P229 Legion',
    [GetHashKey('WEAPON_SOFS')] = 'Sawn Off Shotgun',
    [GetHashKey('WEAPON_FNX')] = 'FNX 45',
    [GetHashKey('WEAPON_G43X')] = 'Glock 43x',
    [GetHashKey('WEAPON_GRENADE')] = 'Grenade',
    [GetHashKey('WEAPON_STICKYBOMB')] = 'Sticky Bomb',
    [GetHashKey('WEAPON_SMOKEGRENADE')] = 'Tear Gas',
    [GetHashKey('WEAPON_BZGAS')] = 'BZ Gas',
    [GetHashKey('WEAPON_MOLOTOV')] = 'Molotov',
    [GetHashKey('WEAPON_FIREEXTINGUISHER')] = 'Fire Extinguisher',
    [GetHashKey('WEAPON_PETROLCAN')] = 'Jerry Can',
    [GetHashKey('OBJECT')] = 'Object',
    [GetHashKey('WEAPON_BALL')] = 'Ball',
    [GetHashKey('WEAPON_FLARE')] = 'Flare',
    [GetHashKey('VEHICLE_WEAPON_TANK')] = 'Tank Cannon',
    [GetHashKey('VEHICLE_WEAPON_SPACE_ROCKET')] = 'Rockets',
    [GetHashKey('VEHICLE_WEAPON_PLAYER_LASER')] = 'Laser',
    [GetHashKey('AMMO_RPG')] = 'Rocket',
    [GetHashKey('AMMO_TANK')] = 'Tank',
    [GetHashKey('AMMO_SPACE_ROCKET')] = 'Rocket',
    [GetHashKey('AMMO_PLAYER_LASER')] = 'Laser',
    [GetHashKey('AMMO_ENEMY_LASER')] = 'Laser',
    [GetHashKey('WEAPON_RAMMED_BY_CAR')] = 'Rammed by Car',
    [GetHashKey('WEAPON_BOTTLE')] = 'Bottle',
    [GetHashKey('WEAPON_GUSENBERG')] = 'Gusenberg Sweeper',
    [GetHashKey('WEAPON_SNSPISTOL')] = 'SNS Pistol',
    [GetHashKey('WEAPON_VINTAGEPISTOL')] = 'Vintage Pistol',
    [GetHashKey('WEAPON_DAGGER')] = 'Antique Cavalry Dagger',
    [GetHashKey('WEAPON_FLAREGUN')] = 'Flare Gun',
    [GetHashKey('WEAPON_HEAVYPISTOL')] = 'Heavy Pistol',
    [GetHashKey('WEAPON_SPECIALCARBINE')] = 'Special Carbine',
    [GetHashKey('WEAPON_MUSKET')] = 'Musket',
    [GetHashKey('WEAPON_FIREWORK')] = 'Firework Launcher',
    [GetHashKey('WEAPON_MARKSMANRIFLE')] = 'Marksman Rifle',
    [GetHashKey('WEAPON_HEAVYSHOTGUN')] = 'Heavy Shotgun',
    [GetHashKey('WEAPON_PROXMINE')] = 'Proximity Mine',
    [GetHashKey('WEAPON_HOMINGLAUNCHER')] = 'Homing Launcher',
    [GetHashKey('WEAPON_HATCHET')] = 'Hatchet',
    [GetHashKey('WEAPON_COMBATPISTOL')] = 'Combat Pistol',
    [GetHashKey('WEAPON_KNUCKLE')] = 'Knuckle Duster',
    [GetHashKey('WEAPON_MARKSMANPISTOL')] = 'Marksman Pistol',
    [GetHashKey('WEAPON_MACHETE')] = 'Machete',
    [GetHashKey('WEAPON_MACHINEPISTOL')] = 'Machine Pistol',
    [GetHashKey('WEAPON_FLASHLIGHT')] = 'Flashlight',
    [GetHashKey('WEAPON_DBSHOTGUN')] = 'Double Barrel Shotgun',
    [GetHashKey('WEAPON_COMPACTRIFLE')] = 'Compact Rifle',
    [GetHashKey('WEAPON_SWITCHBLADE')] = 'Switchblade',
    [GetHashKey('WEAPON_REVOLVER')] = 'Heavy Revolver',
    [GetHashKey('WEAPON_FIRE')] = 'Fire',
    [GetHashKey('WEAPON_HELI_CRASH')] = 'Heli Crash',
    [GetHashKey('WEAPON_RUN_OVER_BY_CAR')] = 'Run over by Car',
    [GetHashKey('WEAPON_HIT_BY_WATER_CANNON')] = 'Hit by Water Cannon',
    [GetHashKey('WEAPON_EXHAUSTION')] = 'Exhaustion',
    [GetHashKey('WEAPON_EXPLOSION')] = 'Explosion',
    [GetHashKey('WEAPON_ELECTRIC_FENCE')] = 'Electric Fence',
    [GetHashKey('WEAPON_BLEEDING')] = 'Bleeding',
    [GetHashKey('WEAPON_DROWNING_IN_VEHICLE')] = 'Drowning in Vehicle',
    [GetHashKey('WEAPON_DROWNING')] = 'Drowning',
    [GetHashKey('WEAPON_BARBED_WIRE')] = 'Barbed Wire',
    [GetHashKey('WEAPON_VEHICLE_ROCKET')] = 'Vehicle Rocket',
    [GetHashKey('WEAPON_BULLPUPRIFLE')] = 'Bullpup Rifle',
    [GetHashKey('WEAPON_ASSAULTSNIPER')] = 'Assault Sniper',
    [GetHashKey('VEHICLE_WEAPON_ROTORS')] = 'Rotors',
    [GetHashKey('WEAPON_RAILGUN')] = 'Railgun',
    [GetHashKey('WEAPON_AIR_DEFENCE_GUN')] = 'Air Defence Gun',
    [GetHashKey('WEAPON_AUTOSHOTGUN')] = 'Automatic Shotgun',
    [GetHashKey('WEAPON_BATTLEAXE')] = 'Battle Axe',
    [GetHashKey('WEAPON_COMPACTLAUNCHER')] = 'Compact Grenade Launcher',
    [GetHashKey('WEAPON_MINISMG')] = 'Mini SMG',
    [GetHashKey('WEAPON_PIPEBOMB')] = 'Pipebomb',
    [GetHashKey('WEAPON_POOLCUE')] = 'Poolcue',
    [GetHashKey('WEAPON_WRENCH')] = 'Wrench',
    [GetHashKey('WEAPON_SNOWBALL')] = 'Snowball',
    [GetHashKey('WEAPON_ANIMAL')] = 'Animal',
    [GetHashKey('WEAPON_COUGAR')] = 'Cougar'
}